import { SIMILARITY_MATCH_COUNT, EMBEDDING_MODEL_NAME } from "./constants.js";
import { genAI, supabase } from "./config.js";

export async function retrieveSimilarDocs(query) {
  // Create vector embeddings based on the query
  const embeddingResponse = await genAI.models.embedContent({
    model: EMBEDDING_MODEL_NAME,
    contents: [query],
  });

  // The vector generated by OpenAI
  const embedding = embeddingResponse.embeddings[0].values;

  //retrieve similar docs from supabase based on embeddings
  const { data: documents, error: matchError } = await supabase.rpc("match_documents", {
    query_embedding: embedding,
    match_count: SIMILARITY_MATCH_COUNT,
  });

  if (matchError) {
    throw new Error(`Failed to fetch docs from supabase. Error: ${matchError}`);
  }

  return documents;
}
